set(_CATKIN_CURRENT_PACKAGE "proyecto_servicios")
set(proyecto_servicios_VERSION "1.0.0")
set(proyecto_servicios_MAINTAINER "asahel <asahel.ht4@gmail.com>")
set(proyecto_servicios_PACKAGE_FORMAT "2")
set(proyecto_servicios_BUILD_DEPENDS "geometry_msgs" "rospy" "sensor_msgs" "std_msgs")
set(proyecto_servicios_BUILD_EXPORT_DEPENDS "geometry_msgs" "rospy" "sensor_msgs" "std_msgs")
set(proyecto_servicios_BUILDTOOL_DEPENDS "catkin")
set(proyecto_servicios_BUILDTOOL_EXPORT_DEPENDS )
set(proyecto_servicios_EXEC_DEPENDS "geometry_msgs" "rospy" "sensor_msgs" "std_msgs")
set(proyecto_servicios_RUN_DEPENDS "geometry_msgs" "rospy" "sensor_msgs" "std_msgs")
set(proyecto_servicios_TEST_DEPENDS )
set(proyecto_servicios_DOC_DEPENDS )
set(proyecto_servicios_URL_WEBSITE "")
set(proyecto_servicios_URL_BUGTRACKER "")
set(proyecto_servicios_URL_REPOSITORY "")
set(proyecto_servicios_DEPRECATED "")